comment out build test release
Signed-off-by: Laurynas Jagutis <laurynas.jagutis@alliander.com>

diff --git a/.github/workflows/build-test-release.yml b/.github/workflows/build-test-release.yml
--- a/.github/workflows/build-test-release.yml
+++ b/.github/workflows/build-test-release.yml
@@ -44,7 +44,9 @@ jobs:
           python set_pypi_version.py
 
       - name: Build SDist
-        run:  python -m build --sdist --outdir wheelhouse .
+        run: | 
+          # python -m build --sdist --outdir wheelhouse .
+          echo "build sdist reached"
 
       - name: Keep version file
         uses: actions/upload-artifact@v4
@@ -76,21 +78,26 @@ jobs:
       - uses: actions/checkout@v4
       - name: Install packages
         run: |
-          sudo apt-get update
-          sudo apt-get install -y ninja-build gcc-13 g++-13 clang-18
-          sudo ln -s /usr/bin/clang-18 /usr/local/bin/clang
-          sudo ln -s /usr/bin/clang++-18 /usr/local/bin/clang++
-          sudo ln -s /usr/bin/gcc-13 /usr/local/bin/gcc
-          sudo ln -s /usr/bin/g++-13 /usr/local/bin/g++
+          # sudo apt-get update
+          # sudo apt-get install -y ninja-build gcc-13 g++-13 clang-18
+          # sudo ln -s /usr/bin/clang-18 /usr/local/bin/clang
+          # sudo ln -s /usr/bin/clang++-18 /usr/local/bin/clang++
+          # sudo ln -s /usr/bin/gcc-13 /usr/local/bin/gcc
+          # sudo ln -s /usr/bin/g++-13 /usr/local/bin/g++
+          echo "clang, gcc packages installed"
 
       - name: Enable brew
         run: |
           echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
       - name: Install C++ dependencies
         run: |
-          brew install boost eigen nlohmann-json msgpack-cxx doctest
+          # brew install boost eigen nlohmann-json msgpack-cxx doctest
+          echo "brew would install boost eigen nlohmann-json msgpack-cxx doctest"
       - name: Build and test
-        run: ./build.sh -p ${{ env.PRESET }} -e -i -t
+        run: |
+          # ./build.sh -p ${{ env.PRESET }} -e -i -t
+          echo "build and test reached"
+
 
   build-cpp-test-windows:
     runs-on: windows-latest
@@ -117,33 +124,35 @@ jobs:
 
       - name: Install conda environment
         run: |
-          conda create --yes -p C:\conda_envs\cpp_pkgs -c conda-forge libboost-headers eigen nlohmann_json msgpack-cxx doctest
+          # conda create --yes -p C:\conda_envs\cpp_pkgs -c conda-forge libboost-headers eigen nlohmann_json msgpack-cxx doctest
+          echo "installing conda env"
 
       - name: Build and test
         run: |
-          $vsPath = &(Join-Path ${env:ProgramFiles(x86)} '\Microsoft Visual Studio\Installer\vswhere.exe') -property installationpath
-          Import-Module (Join-Path $vsPath 'Common7\Tools\Microsoft.VisualStudio.DevShell.dll')
-          Enter-VsDevShell -VsInstallPath $vsPath -SkipAutomaticLocation -DevCmdArguments '-arch=x64 -host_arch=x64'
+          # $vsPath = &(Join-Path ${env:ProgramFiles(x86)} '\Microsoft Visual Studio\Installer\vswhere.exe') -property installationpath
+          # Import-Module (Join-Path $vsPath 'Common7\Tools\Microsoft.VisualStudio.DevShell.dll')
+          # Enter-VsDevShell -VsInstallPath $vsPath -SkipAutomaticLocation -DevCmdArguments '-arch=x64 -host_arch=x64'
 
-          # Resolve dirty PATH environment
-          # TODO(mgovers): Remove after https://github.com/actions/runner-images/issues/10001 is resolved
-          $env:PATH = ($env:PATH -split ';' | Where-Object { $_ -ne 'C:\Program Files\LLVM\bin' }) -join ';'
+          # # Resolve dirty PATH environment
+          # # TODO(mgovers): Remove after https://github.com/actions/runner-images/issues/10001 is resolved
+          # $env:PATH = ($env:PATH -split ';' | Where-Object { $_ -ne 'C:\Program Files\LLVM\bin' }) -join ';'
 
-          # generate cmake cache
-          cmake --preset ${{ env.PRESET }} -DCMAKE_PREFIX_PATH=C:\conda_envs\cpp_pkgs\Library; if(!$?) { Exit $LASTEXITCODE }
-          # build
-          cmake --build --preset ${{ env.PRESET }} --verbose -j 1; if(!$?) { Exit $LASTEXITCODE }
-          # test
-          ctest --preset ${{ env.PRESET }} --output-on-failure; if(!$?) { Exit $LASTEXITCODE }
-          # install
-          cmake --build --preset ${{ env.PRESET }} --verbose -j 1 --target install; if(!$?) { Exit $LASTEXITCODE }
+          # # generate cmake cache
+          # cmake --preset ${{ env.PRESET }} -DCMAKE_PREFIX_PATH=C:\conda_envs\cpp_pkgs\Library; if(!$?) { Exit $LASTEXITCODE }
+          # # build
+          # cmake --build --preset ${{ env.PRESET }} --verbose -j 1; if(!$?) { Exit $LASTEXITCODE }
+          # # test
+          # ctest --preset ${{ env.PRESET }} --output-on-failure; if(!$?) { Exit $LASTEXITCODE }
+          # # install
+          # cmake --build --preset ${{ env.PRESET }} --verbose -j 1 --target install; if(!$?) { Exit $LASTEXITCODE }
 
-          # build and run integration test
-          cd tests/package_tests; if(!$?) { Exit $LASTEXITCODE }
-          cmake --preset ${{ env.PRESET }}; if(!$?) { Exit $LASTEXITCODE }
-          cmake --build --preset ${{ env.PRESET }} --verbose -j 1; if(!$?) { Exit $LASTEXITCODE }
-          cmake --build --preset ${{ env.PRESET }} --verbose -j 1 --target install; if(!$?) { Exit $LASTEXITCODE }
-          install\${{ env.PRESET }}\bin\power_grid_model_package_test; if(!$?) { Exit $LASTEXITCODE }
+          # # build and run integration test
+          # cd tests/package_tests; if(!$?) { Exit $LASTEXITCODE }
+          # cmake --preset ${{ env.PRESET }}; if(!$?) { Exit $LASTEXITCODE }
+          # cmake --build --preset ${{ env.PRESET }} --verbose -j 1; if(!$?) { Exit $LASTEXITCODE }
+          # cmake --build --preset ${{ env.PRESET }} --verbose -j 1 --target install; if(!$?) { Exit $LASTEXITCODE }
+          # install\${{ env.PRESET }}\bin\power_grid_model_package_test; if(!$?) { Exit $LASTEXITCODE }
+          echo "build and test reached"
 
   build-cpp-test-macos:
     runs-on: macos-14
@@ -164,10 +173,13 @@ jobs:
 
       - name: Install cpp dependencies
         run: |
-          brew install ninja boost eigen nlohmann-json msgpack-cxx doctest
+          # brew install ninja boost eigen nlohmann-json msgpack-cxx doctest
+          echo "install cpp dependencies reached"
 
       - name: Build and test
-        run: ./build.sh -p ${{ env.PRESET }} -e -i -t
+        run: |
+          # ./build.sh -p ${{ env.PRESET }} -e -i -t
+          echo "Build and test reached"
 
   build-and-test-python:
     strategy:
@@ -254,25 +266,31 @@ jobs:
       - name: Build and install cmake target for Windows
         if: matrix.os == 'windows'
         run: |          
-          $vsPath = &(Join-Path ${env:ProgramFiles(x86)} '\Microsoft Visual Studio\Installer\vswhere.exe') -property installationpath
-          Import-Module (Join-Path $vsPath 'Common7\Tools\Microsoft.VisualStudio.DevShell.dll')
-          Enter-VsDevShell -VsInstallPath $vsPath -SkipAutomaticLocation -DevCmdArguments '-arch=x64 -host_arch=x64'
-          cmake -GNinja -DCMAKE_BUILD_TYPE=Release -B build/ -S .
-          cmake --build build/ --verbose -j1
-          cmake --install build/ --prefix ${env:CONDA_PREFIX}/Library
+          # $vsPath = &(Join-Path ${env:ProgramFiles(x86)} '\Microsoft Visual Studio\Installer\vswhere.exe') -property installationpath
+          # Import-Module (Join-Path $vsPath 'Common7\Tools\Microsoft.VisualStudio.DevShell.dll')
+          # Enter-VsDevShell -VsInstallPath $vsPath -SkipAutomaticLocation -DevCmdArguments '-arch=x64 -host_arch=x64'
+          # cmake -GNinja -DCMAKE_BUILD_TYPE=Release -B build/ -S .
+          # cmake --build build/ --verbose -j1
+          # cmake --install build/ --prefix ${env:CONDA_PREFIX}/Library
+          echo "Build and install cmake target for Windows reached"
 
       - name: Build and install cmake target for Linux
         if: matrix.os == 'ubuntu'
         run: |
-          cmake -GNinja -DCMAKE_BUILD_TYPE=Release -B build/ -S . -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX -DCMAKE_PREFIX_PATH=$CONDA_PREFIX
-          cmake --build build/ --verbose -j1
-          cmake --install build/      
+          # cmake -GNinja -DCMAKE_BUILD_TYPE=Release -B build/ -S . -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX -DCMAKE_PREFIX_PATH=$CONDA_PREFIX
+          # cmake --build build/ --verbose -j1
+          # cmake --install build/
+          echo "Build and install cmake target for Linux reached"
 
       - name: Build python
-        run: python -m pip install . -vv --no-build-isolation --no-deps   
+        run: |
+          # python -m pip install . -vv --no-build-isolation --no-deps  
+          echo "Build python reached" 
 
       - name: Test
-        run: pytest
+        run: | 
+          # pytest
+          echo "pytest reached"
 
   publish-wheels:
     needs: [build-cpp-test-linux, build-cpp-test-windows, build-cpp-test-macos, build-and-test-python, build-and-test-conda]
@@ -325,7 +343,9 @@ jobs:
         run: |
           pip install twine
           echo "Publish to PyPI..."
-          twine upload --verbose wheelhouse/*
+          # twine upload --verbose wheelhouse/*
+          echo "Contents of wheelhouse:"
+          ls -lh wheelhouse
 
       - name: Release
         uses: softprops/action-gh-release@v2
